import ApiDoc from './src/api-doc'
import ArtDoc from './src/art-doc'
import Avatar from './src/avatar'
import BehavioursDoc from './src/behaviours-doc'
import Blog from './src/blog'
import Conduct from './src/conduct'
import EventPage from './src/event-page'
import Explore from './src/explore'
import Parcel from './src/parcel'
import Parcels from './src/parcels'
import PostPage from './src/post'
import Privacy from './src/privacy'
import Space from './src/space'
import Terms from './src/terms'
import Womp from './src/womp'

import * as passport from 'passport'
import cache from '../server/cache'
import renderComponent from '../server/handlers/render-component'
import { isOwner, isValidUUID } from '../server/lib/helpers'

import { queryAndCallback } from '../server/lib/query-helpers'
import db from '../server/pg'
import LoadingPage from './src/loading-page'
import { shellRoutes } from './src/routes'

import { Express } from 'express'
import path from 'path'
import { SUPPORTED_CHAINS_BY_ID } from '../common/helpers/chain-helpers'
import NotFound from './src/not-found'

const renderPage = (content: any) => renderComponent(content)

export default function loadRoutes(app: Express) {
  const duration = '10 minutes'

  app.get('/', cache(duration), (req, res) => {
    res.send(renderPage(<Explore />))
  })

  app.get('/explore', cache(duration), (req, res) => {
    res.send(renderPage(<Explore />))
  })

  app.get('/terms', cache(duration), (req, res) => {
    res.send(renderPage(<Terms />))
  })

  app.get('/privacy', cache(duration), (req, res) => {
    res.send(renderPage(<Privacy />))
  })

  app.get('/conduct', cache(duration), (req, res) => {
    res.send(renderPage(<Conduct />))
  })

  app.get('/behaviours', cache(duration), (req, res) => {
    res.send(renderPage(<BehavioursDoc />))
  })

  app.get('/BEHAVIOURS.md', cache(duration), (req, res) => {
    res.sendFile(path.join(__dirname, '..', 'BEHAVIOURS.md'))
  })

  app.get('/art', cache(duration), (req, res) => {
    res.send(renderPage(<ArtDoc />))
  })

  app.get('/ART.md', cache(false), (req, res) => {
    res.sendFile(path.join(__dirname, '..', 'ART.md'))
  })

  app.get('/api', cache(duration), (req, res) => {
    res.send(renderPage(<ApiDoc />))
  })

  // generated by npm run docs:api, alongside llms.txt and the spec it reads
  app.get('/API.md', cache(duration), (req, res) => {
    res.sendFile(path.join(__dirname, '..', 'API.md'))
  })

  app.get('/llms.txt', cache(duration), (req, res) => {
    res.sendFile(path.join(__dirname, '..', 'llms.txt'))
  })

  app.get('/openapi.yaml', cache(duration), (req, res) => {
    res.type('text/yaml').sendFile(path.join(__dirname, '..', 'server', 'openapi.yaml'))
  })

  app.get('/not-found', cache(duration), (req, res) => {
    res.send(renderPage(<NotFound path="/not-found" />))
  })
  app.get('/parcels', cache(duration), (req, res) => {
    const limit = typeof req.query.limit === 'string' ? parseInt(req.query.limit, 100) : NaN
    const page = typeof req.query.page === 'string' ? parseInt(req.query.page, 10) : NaN

    if (req.query.owner || req.query.q) {
      res.send(renderPage(<LoadingPage />))
      return
    }

    queryAndCallback(db, 'parcels/search-parcels', 'parcels', [`%${req.query.q || ''}%`, isNaN(limit) ? null : limit, isNaN(page) ? null : page, req.query.sort ? req.query.sort : 'id', true], (response) => {
      res.send(renderPage(<Parcels parcels={response.success ? response.parcels : []} />))
    })
  })

  // longish cache on the page, but only 5 second cache on the API
  // so if out of date, will update shortly after page load
  app.get('/parcels/:id', cache('10 seconds'), passport.authenticate(['jwt', 'anonymous'], { session: false }), (req, res) => {
    const id = parseInt(req.params.id, 10)
    if (isNaN(id)) {
      res.status(404).json({ success: false, message: 'not found' })
      return
    }

    queryAndCallback(db, 'get-parcel', 'parcel', [id, isOwner(req)], (response) => {
      if (!response.success) {
        res.status(404).json({ success: false, message: 'not found' })
        return
      }

      if (response.parcel?.updated_at) {
        const lastModified = new Date(response.parcel.updated_at)
        if (!isNaN(lastModified.getTime())) {
          res.setHeader('Last-Modified', lastModified.toUTCString())
        }
      }

      res.send(renderPage(<Parcel parcel={response.parcel} />))
    })
  })

  app.get('/womps/:id', (req, res) => {
    const id = parseInt(req.params.id, 10)
    if (isNaN(id)) {
      return res.status(404).json({ success: false, message: 'womp not found' })
    }
    queryAndCallback(db, 'womps/get-womp', 'womp', [id], (response) => {
      if (!response.success) {
        res.send(renderPage(<LoadingPage />))
        return
      }
      res.send(renderPage(<Womp womp={response.womp} id={response.womp.id} />))
    })
  })

  // blog: SSR so X / Discord / Slack get og + twitter cards (shell alone has none)
  app.get('/blog', cache(duration), (_req, res) => {
    res.send(renderPage(<Blog />))
  })

  app.get('/blog/:slug', cache('1 minute'), async (req, res) => {
    const slug = req.params.slug
    if (typeof slug !== 'string' || !slug) {
      return res.status(404).send(renderPage(<NotFound />))
    }

    try {
      const post = await db.query(
        'embedded/ssr-get-post',
        `select p.slug, p.title, p.body, p.created_at,
          CASE
            WHEN p.author = 'voxels' THEN to_json(p.author::text)
            ELSE COALESCE(
              (SELECT row_to_json(sub) FROM (SELECT a.name, a.owner FROM avatars a WHERE lower(a.owner) = lower(p.author) LIMIT 1) sub),
              to_json(p.author)
            )
          END as author
         from posts p where p.slug = $1`,
        [slug],
      )
      if (!(post.rows?.length ?? 0)) {
        return res.status(404).send(renderPage(<NotFound />))
      }

      const comments = await db.query(
        'embedded/ssr-get-comments',
        `select c.id, c.body, c.created_at,
          COALESCE(
            (SELECT row_to_json(sub) FROM (SELECT a.name, a.owner FROM avatars a WHERE lower(a.owner) = lower(c.owner) LIMIT 1) sub),
            to_json(c.owner)
          ) as author
         from comments c
         where c.commentable_type = 'Post' and c.commentable_id = $1
         order by c.created_at asc`,
        [slug],
      )

      res.send(renderPage(<PostPage slug={slug} post={post.rows![0]} comments={comments.rows ?? []} />))
    } catch {
      res.status(500).send(renderPage(<LoadingPage />))
    }
  })

  app.get(['/avatar/:walletOrName', '/avatar/:walletOrName/:tab?', '/u/:walletOrName', '/u/:walletOrName/:tab?'], (req, res) => {
    const walletOrName = req.params.walletOrName
    queryAndCallback(db, 'get-avatar-by-name-or-wallet', 'avatar', [walletOrName], (response) => {
      if (!response.success) {
        res.send(renderPage(<NotFound />))
        return
      }
      res.send(renderPage(<Avatar avatar={response.avatar} tab={req.params.tab} />))
    })
  })

  // app.get('/events/:id', (req, res) => {
  //   const id = parseInt(req.params.id, 10)
  //   if (isNaN(id)) {
  //     return res.status(404).json({ success: false, message: 'event not found' })
  //   }
  //   queryAndCallback(db, 'events/get-event', 'event', [id], (response) => {
  //     if (!response.success) {
  //       res.send(renderPage(<NotFound />))
  //       return
  //     }
  //     res.send(renderPage(<EventPage event={response.event} />))
  //   })
  // })

  app.get('/collections/:collection_id/:token_id', cache('1 minute'), (req, res) => {
    const id = parseInt(req.params.collection_id, 10)
    const token_id = parseInt(req.params.token_id, 10)
    if (isNaN(token_id)) {
      return res.status(404).json({ success: false, message: 'wearable not found' })
    }
    if (isNaN(id)) {
      return res.status(404).json({ success: false, message: 'wearable not found' })
    }
    queryAndCallback(db, 'collectibles/get-collectible', 'wearable', [id, token_id], (response) => {
      if (!response.success) {
        res.redirect(404, '/not-found')
        return
      }
      const chain_identifier = SUPPORTED_CHAINS_BY_ID[response.wearable.chain_id] || 'eth'
      res.redirect(302, `/collections/${chain_identifier}/${response.wearable.collection_address}/${token_id}`)
    })
  })

  // These routes don't have any static content, are only available in the bundle
  app.get('/account/go-live/broadcast', (req, res) => {
    const q = req.originalUrl.includes('?') ? req.originalUrl.slice(req.originalUrl.indexOf('?')) : ''
    res.redirect(301, `/golive/broadcast${q}`)
  })
  app.get('/account/go-live', (req, res) => {
    const q = req.originalUrl.includes('?') ? req.originalUrl.slice(req.originalUrl.indexOf('?')) : ''
    res.redirect(301, `/golive${q}`)
  })

  shellRoutes.forEach((r) => {
    app.get(r.path, cache(r.cache as any), (req, res) => {
      res.send(renderPage(<LoadingPage />))
    })
  })

  app.get('/spaces', (_req, res) => {
    res.redirect('/')
  })

  app.get('/spaces/:id/play', (_req, res) => {
    res.redirect('/spaces')
  })

  app.get('/spaces/:id', cache('1 minute'), passport.authenticate(['jwt', 'anonymous'], { session: false }), (req, res) => {
    if (!req.params.id || !isValidUUID(req.params.id)) {
      return res.status(404).json({ success: false, message: 'space not found' })
    }

    queryAndCallback(db, 'spaces/get-space-content', 'space', [req.params.id], (response) => {
      if (!response.success) {
        res.redirect('/not-found')
        return
      }
      res.send(renderPage(<Space space={response.space} />))
    })
  })
}
